### PR TITLE
[wip] test output modification

### PR DESCRIPTION
**Pull request by djarecka**
* allowing for test output to have "2d structure", i.e. `{"key_n": list_n}`, one of the key has to be `col_names`

* checking if results from different tests can be merged: assuming that you can merge tests that either have flat structure or have the same `col_names`

in addition:
* allowing for an empty list in `plots["var_list"]` in parameter file, using some default choice in each altair plot 

TODO:

- [x] updating simple workflow

- [ ] using a wild card in files names

- [x] proper merging for multiple tests (that have multiple files)

### CODE REVIEW

**Comment by djarecka** [comment]
I haven't fix the wild card issue, but I will merge this PR, want to test other things now. But now we can have tests that take multiple files and can return `{key: list}` and the results from various tests are properly merged and presented on parallel plot, for my fake-toy example you can see dashboard [here](https://200-111057450-gh.circle-artifacts.com/0/home/circleci/regtests/fake_list_cwl/index.html).

Unfortunately I still don't know why in case of simple workflow (with all tests returning 0) the plot doesn't look good, see [here](https://200-111057450-gh.circle-artifacts.com/0/home/circleci/regtests/simple_workflow_cwl/index.html)

**Comment by satra** [comment]
@djarecka - can you point me to the csv file you are generating for simple workflow? also did you generate the osx version for simple workflow?

**Comment by satra** [comment]
i'm running it now on osx

**Comment by djarecka** [comment]
@I'm testing a different expected output in a different PR (yesterday it was failing due to some problems on CircleCI, but I'd think that should pass now):
https://github.com/djarecka/regtests/pull/13

**Comment by djarecka** [comment]
oh, I actually temporary created a PR to my fork, that's why you couldn't see it

**Comment by djarecka** [comment]
@satra -and the csv: https://200-111057450-gh.circle-artifacts.com/0/home/circleci/regtests/simple_workflow_cwl/output_all.csv

**Comment by satra** [comment]
i see the same here: http://syntagmatic.github.io/parallel-coordinates/examples/upload.html

so it must be something to do with a single value that is 0.

**Comment by djarecka** [comment]
I actually can easily check if it's ok for a single value that is != 0, and it looks fine when I put ones instead of zeros.

**Pull request merged**
