### PR TITLE
[WIP] Neurodocker pip

### PR DESCRIPTION
**Pull request by djarecka**
@kaczmarj - I created two extra workflows, one that uses `numpa` installed with `conda`: `sorting_array_conda`, and the second that required `pip`: `sorting_array_pip`. Of course, the second one doesn't work now.

I added a new key `pip_install` to parameter file, but feel free to suggest other key or syntax.

Will you find time to finish this PR?

### CODE REVIEW

**Comment by kaczmarj** [comment]
@djarecka - does this form below install numpy through `conda`?

```json
 "python": [
    "2.7 numpy",
    "3.5 numpy"
]
```

i like the form:

```json
"python": [
    "2.7",
    "3.5"
],
"pip_install": [
    "numpy"
]
```

but i'm wondering whether we should have `python`, `conda_install`, and `pip_install`. what do you think?

**Comment by djarecka** [comment]
@kaczmarj - yes, the first example is working, I was testing it.
I was actually wondering about the same, is it ok if we keep conda as default and only if we need pip we use `pip_install`.

But now I think we should probably use both `conda_install` and `pip_install` as you suggested. It's likely that people would want to test for different version of python, but they usually want to have the same libraries, so let's keep in `"python"` only the version, and all other libraries we should put in `conda_install` or`pip_install`.

**Comment by djarecka** [comment]
let me know if you want me to push one extra commit to change the syntax of the first example with conda

**Comment by kaczmarj** [comment]
i think the syntax with `python`, `conda_install`, and `pip_install` would be best

**Comment by kaczmarj** [comment]
@djarecka - i'm really sorry i took so long with this.

i've been trying to implement this, and i think the best option is below. i'll update the files now.

```json
"python": {
  "version": ["2.7", "3.5"],
  "pip_install": ["numpy"],
  "conda_install": ["traits"]
}
```

**Pull request merged**
